services:
  - type: web
    name: mediexpert-plus
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MEDIEXPERT_SECRET_KEY
        generateValue: true
