import json
from pathlib import Path


path = Path("static/data/disease_info.json")
data = json.loads(path.read_text(encoding="utf-8"))

common_advice = "This is AI-assisted guidance. Consult a qualified doctor for confirmation, prescriptions, severe symptoms, pregnancy, children, elderly patients, or long-lasting illness."

diseases = {
    "Fungal infection": {
        "description": "A fungal infection affects the skin, nails, or moist body areas and can cause itching, redness, scaling, or ring-shaped rashes.",
        "medicines": ["Clotrimazole cream", "Antifungal powder", "Cetirizine"],
        "dosage": {"Clotrimazole cream": "Apply thinly twice daily for 2-4 weeks.", "Antifungal powder": "Dust affected area once or twice daily.", "Cetirizine": "10 mg once daily at night if itching is troublesome."},
        "precautions": ["Keep the area clean and dry.", "Avoid sharing towels or clothing.", "Wear loose cotton clothes.", "Continue treatment for the advised duration."],
        "advice": common_advice,
    },
    "Allergy": {
        "description": "Allergy is an immune reaction to triggers such as dust, pollen, foods, medicines, or insect bites.",
        "medicines": ["Cetirizine", "Levocetirizine", "Saline nasal spray"],
        "dosage": {"Cetirizine": "10 mg once daily when needed.", "Levocetirizine": "5 mg once at night.", "Saline nasal spray": "1-2 sprays per nostril as needed."},
        "precautions": ["Avoid known allergens.", "Use a mask in dusty areas.", "Seek urgent help for breathing difficulty or swelling of lips/face."],
        "advice": common_advice,
    },
    "GERD": {
        "description": "GERD is acid reflux where stomach acid flows back into the food pipe, causing burning chest discomfort, sour taste, or belching.",
        "medicines": ["Antacid", "Pantoprazole", "Oral rehydration fluids"],
        "dosage": {"Antacid": "Take after meals as per label.", "Pantoprazole": "40 mg before breakfast only if advised by a clinician.", "Oral rehydration fluids": "Sip as needed."},
        "precautions": ["Avoid spicy, oily, and late-night meals.", "Do not lie down immediately after eating.", "Elevate head while sleeping.", "Limit caffeine and alcohol."],
        "advice": common_advice,
    },
    "Chronic cholestasis": {
        "description": "Chronic cholestasis is reduced bile flow that can cause itching, jaundice, dark urine, pale stools, and fatigue.",
        "medicines": ["Doctor-prescribed bile therapy", "Vitamin supplements", "Itch-relief medicines"],
        "dosage": {"Doctor-prescribed bile therapy": "Use only under specialist advice.", "Vitamin supplements": "As prescribed after blood tests.", "Itch-relief medicines": "Use as advised by doctor."},
        "precautions": ["Consult a gastroenterologist.", "Avoid alcohol.", "Monitor yellowing of eyes and urine color.", "Do liver function tests as advised."],
        "advice": common_advice,
    },
    "Drug Reaction": {
        "description": "A drug reaction is an unwanted response to a medicine, commonly causing rash, itching, swelling, fever, or breathing difficulty.",
        "medicines": ["Antihistamine", "Calamine lotion", "Emergency care if severe"],
        "dosage": {"Antihistamine": "Use as per label or doctor advice.", "Calamine lotion": "Apply 2-3 times daily.", "Emergency care if severe": "Seek immediate medical help."},
        "precautions": ["Stop the suspected medicine only after medical advice unless symptoms are severe.", "Record the drug name.", "Seek urgent care for swelling, wheezing, or widespread rash."],
        "advice": common_advice,
    },
    "Peptic ulcer diseae": {
        "description": "Peptic ulcer disease is a sore in the stomach or upper intestine, often causing burning stomach pain, nausea, bloating, or black stools.",
        "medicines": ["Pantoprazole", "Antacid", "Doctor-prescribed antibiotics"],
        "dosage": {"Pantoprazole": "40 mg before breakfast if prescribed.", "Antacid": "After meals as per label.", "Doctor-prescribed antibiotics": "Complete the full course only if prescribed."},
        "precautions": ["Avoid painkillers like ibuprofen unless advised.", "Avoid alcohol and smoking.", "Eat smaller meals.", "Seek urgent care for vomiting blood or black stools."],
        "advice": common_advice,
    },
    "AIDS": {
        "description": "AIDS is an advanced stage of HIV infection that weakens immunity and increases risk of serious infections.",
        "medicines": ["Antiretroviral therapy", "Treatment for infections", "Nutritional supplements"],
        "dosage": {"Antiretroviral therapy": "Must be prescribed and monitored by an HIV specialist.", "Treatment for infections": "As prescribed.", "Nutritional supplements": "As advised."},
        "precautions": ["Get confirmatory HIV testing.", "Do not share needles.", "Practice safe sex.", "Continue regular specialist follow-up."],
        "advice": common_advice,
    },
    "Diabetes ": {
        "description": "Diabetes is a condition with high blood sugar due to problems with insulin production or action.",
        "medicines": ["Doctor-prescribed diabetes medicine", "Oral rehydration fluids", "Glucose monitoring"],
        "dosage": {"Doctor-prescribed diabetes medicine": "Take only as prescribed.", "Oral rehydration fluids": "Use during dehydration.", "Glucose monitoring": "Check as advised."},
        "precautions": ["Monitor blood sugar.", "Reduce sugary foods and refined carbs.", "Exercise regularly.", "Do not skip prescribed medicines."],
        "advice": common_advice,
    },
    "Gastroenteritis": {
        "description": "Gastroenteritis is stomach and intestine inflammation causing vomiting, diarrhea, stomach cramps, and dehydration.",
        "medicines": ["ORS", "Zinc supplements", "Probiotic"],
        "dosage": {"ORS": "Sip frequently after every loose stool or vomiting.", "Zinc supplements": "Use as age-appropriate advice.", "Probiotic": "As per label for 3-5 days."},
        "precautions": ["Drink plenty of fluids.", "Eat light food.", "Avoid street food and dairy temporarily.", "Seek care for blood in stool or dehydration."],
        "advice": common_advice,
    },
    "Bronchial Asthma": {
        "description": "Bronchial asthma causes airway narrowing and inflammation, leading to wheezing, cough, chest tightness, and breathlessness.",
        "medicines": ["Salbutamol inhaler", "Controller inhaler", "Steam inhalation"],
        "dosage": {"Salbutamol inhaler": "Use only as prescribed for acute symptoms.", "Controller inhaler": "Use daily only if prescribed.", "Steam inhalation": "Use warm steam carefully if it helps congestion."},
        "precautions": ["Avoid smoke, dust, and triggers.", "Keep prescribed inhaler available.", "Seek emergency care for severe breathlessness.", "Use inhaler technique correctly."],
        "advice": common_advice,
    },
    "Hypertension ": {
        "description": "Hypertension means blood pressure remains high, increasing risk to the heart, brain, kidneys, and eyes.",
        "medicines": ["Doctor-prescribed BP medicine", "Low-salt diet", "Home BP monitoring"],
        "dosage": {"Doctor-prescribed BP medicine": "Take exactly as prescribed.", "Low-salt diet": "Limit added salt daily.", "Home BP monitoring": "Record readings regularly."},
        "precautions": ["Reduce salt.", "Exercise regularly.", "Avoid tobacco.", "Seek urgent care for chest pain, severe headache, or weakness."],
        "advice": common_advice,
    },
    "Migraine": {
        "description": "Migraine is a recurrent headache disorder often causing one-sided throbbing pain, nausea, light sensitivity, and visual symptoms.",
        "medicines": ["Paracetamol", "Ibuprofen", "Doctor-prescribed migraine medicine"],
        "dosage": {"Paracetamol": "500 mg every 6 hours if needed, within safe daily limits.", "Ibuprofen": "400 mg after food if suitable.", "Doctor-prescribed migraine medicine": "Use as directed."},
        "precautions": ["Rest in a dark quiet room.", "Hydrate well.", "Identify triggers.", "Seek care for sudden worst headache or neurological symptoms."],
        "advice": common_advice,
    },
    "Cervical spondylosis": {
        "description": "Cervical spondylosis is age- or posture-related wear in the neck spine, causing neck pain, stiffness, or arm symptoms.",
        "medicines": ["Paracetamol", "Topical pain-relief gel", "Physiotherapy"],
        "dosage": {"Paracetamol": "500 mg every 6 hours if needed within safe limits.", "Topical pain-relief gel": "Apply 2-3 times daily.", "Physiotherapy": "As advised by therapist."},
        "precautions": ["Maintain good posture.", "Avoid prolonged phone bending.", "Use ergonomic support.", "Seek care for weakness or numbness."],
        "advice": common_advice,
    },
    "Paralysis (brain hemorrhage)": {
        "description": "Paralysis from brain hemorrhage is a medical emergency caused by bleeding in the brain, often with weakness, speech trouble, or altered consciousness.",
        "medicines": ["Emergency hospital care", "Blood pressure control", "Rehabilitation"],
        "dosage": {"Emergency hospital care": "Call emergency services immediately.", "Blood pressure control": "Hospital-supervised.", "Rehabilitation": "As prescribed after stabilization."},
        "precautions": ["Do not delay emergency care.", "Do not give food or drink if consciousness is altered.", "Note symptom start time."],
        "advice": "Emergency warning: seek immediate medical care.",
    },
    "Jaundice": {
        "description": "Jaundice causes yellow eyes or skin due to raised bilirubin and may be linked to liver, bile duct, or blood disorders.",
        "medicines": ["Doctor evaluation", "Hydration", "Vitamin support"],
        "dosage": {"Doctor evaluation": "Required for cause-based treatment.", "Hydration": "Drink fluids unless restricted.", "Vitamin support": "Only if advised."},
        "precautions": ["Avoid alcohol.", "Do liver tests.", "Avoid self-medication.", "Seek care for confusion, bleeding, or severe weakness."],
        "advice": common_advice,
    },
    "Malaria": {
        "description": "Malaria is a mosquito-borne infection causing fever with chills, sweating, headache, body pain, and weakness.",
        "medicines": ["Antimalarial medicine", "Paracetamol", "ORS"],
        "dosage": {"Antimalarial medicine": "Use only after testing and prescription.", "Paracetamol": "500 mg every 6 hours for fever within safe limits.", "ORS": "Sip regularly."},
        "precautions": ["Get malaria test.", "Use mosquito nets and repellents.", "Remove stagnant water.", "Complete prescribed course."],
        "advice": common_advice,
    },
    "Chicken pox": {
        "description": "Chicken pox is a contagious viral illness with fever and itchy fluid-filled blisters.",
        "medicines": ["Calamine lotion", "Paracetamol", "Antihistamine"],
        "dosage": {"Calamine lotion": "Apply 2-3 times daily.", "Paracetamol": "Use for fever within safe limits.", "Antihistamine": "At night if itching is severe."},
        "precautions": ["Isolate until lesions crust.", "Avoid scratching.", "Keep nails short.", "Avoid aspirin."],
        "advice": common_advice,
    },
    "Dengue": {
        "description": "Dengue is a mosquito-borne viral fever that can cause high fever, severe body pain, rash, and low platelets.",
        "medicines": ["Paracetamol", "ORS", "Doctor monitoring"],
        "dosage": {"Paracetamol": "Use only within safe limits for fever.", "ORS": "Sip frequently.", "Doctor monitoring": "Platelet and warning-sign monitoring as advised."},
        "precautions": ["Avoid ibuprofen and aspirin.", "Hydrate well.", "Watch for bleeding, severe abdominal pain, or drowsiness.", "Prevent mosquito bites."],
        "advice": common_advice,
    },
    "Typhoid": {
        "description": "Typhoid is a bacterial infection causing prolonged fever, weakness, stomach pain, and digestive symptoms.",
        "medicines": ["Doctor-prescribed antibiotics", "Paracetamol", "ORS"],
        "dosage": {"Doctor-prescribed antibiotics": "Complete full prescribed course.", "Paracetamol": "Use within safe limits for fever.", "ORS": "Sip as needed."},
        "precautions": ["Get medical testing.", "Drink safe water.", "Eat hygienic food.", "Complete antibiotics if prescribed."],
        "advice": common_advice,
    },
    "hepatitis A": {
        "description": "Hepatitis A is a viral liver infection spread through contaminated food or water, causing fever, nausea, abdominal pain, and jaundice.",
        "medicines": ["Rest", "Hydration", "Doctor monitoring"],
        "dosage": {"Rest": "Adequate rest until recovery.", "Hydration": "Drink fluids regularly.", "Doctor monitoring": "Liver tests as advised."},
        "precautions": ["Avoid alcohol.", "Eat safe food.", "Wash hands often.", "Avoid unnecessary medicines."],
        "advice": common_advice,
    },
    "Hepatitis B": {
        "description": "Hepatitis B is a viral liver infection spread through blood and body fluids and can become chronic.",
        "medicines": ["Specialist antiviral therapy", "Liver monitoring", "Vaccination for contacts"],
        "dosage": {"Specialist antiviral therapy": "Only under specialist care.", "Liver monitoring": "As advised.", "Vaccination for contacts": "As per vaccine schedule."},
        "precautions": ["Avoid sharing razors/needles.", "Practice safe sex.", "Avoid alcohol.", "Follow up with liver specialist."],
        "advice": common_advice,
    },
    "Hepatitis C": {
        "description": "Hepatitis C is a viral liver infection usually spread through blood exposure and may become chronic.",
        "medicines": ["Direct-acting antivirals", "Liver monitoring", "Vaccination for hepatitis A/B if advised"],
        "dosage": {"Direct-acting antivirals": "Specialist-prescribed course.", "Liver monitoring": "As advised.", "Vaccination for hepatitis A/B if advised": "As per schedule."},
        "precautions": ["Avoid alcohol.", "Do not share needles or razors.", "Get specialist treatment.", "Screen close risk contacts."],
        "advice": common_advice,
    },
    "Hepatitis D": {
        "description": "Hepatitis D is a serious liver infection that occurs only with hepatitis B infection.",
        "medicines": ["Specialist care", "Antiviral treatment", "Liver monitoring"],
        "dosage": {"Specialist care": "Required.", "Antiviral treatment": "Only as prescribed.", "Liver monitoring": "As advised."},
        "precautions": ["Manage hepatitis B.", "Avoid alcohol.", "Prevent blood/body fluid exposure.", "Follow specialist care."],
        "advice": common_advice,
    },
    "Hepatitis E": {
        "description": "Hepatitis E is a viral liver infection often spread by contaminated water and can be serious in pregnancy.",
        "medicines": ["Rest", "Hydration", "Doctor monitoring"],
        "dosage": {"Rest": "Adequate rest.", "Hydration": "Drink safe fluids.", "Doctor monitoring": "Liver tests as advised."},
        "precautions": ["Drink safe water.", "Avoid alcohol.", "Pregnant patients need urgent medical care.", "Maintain hand hygiene."],
        "advice": common_advice,
    },
    "Alcoholic hepatitis": {
        "description": "Alcoholic hepatitis is liver inflammation due to alcohol use, causing jaundice, weakness, abdominal swelling, or fever.",
        "medicines": ["Alcohol cessation support", "Nutritional therapy", "Specialist treatment"],
        "dosage": {"Alcohol cessation support": "Start immediately with medical support.", "Nutritional therapy": "As advised.", "Specialist treatment": "Depends on severity."},
        "precautions": ["Stop alcohol.", "Consult liver specialist.", "Avoid self-medication.", "Seek urgent care for confusion or bleeding."],
        "advice": common_advice,
    },
    "Tuberculosis": {
        "description": "Tuberculosis is a bacterial infection, commonly affecting lungs, causing cough, fever, night sweats, weight loss, and fatigue.",
        "medicines": ["Anti-TB treatment", "Nutritional support", "Fever medicine"],
        "dosage": {"Anti-TB treatment": "Must follow government/doctor-prescribed regimen.", "Nutritional support": "Protein-rich diet as tolerated.", "Fever medicine": "Paracetamol within safe limits."},
        "precautions": ["Get sputum/chest testing.", "Wear mask until advised.", "Complete full treatment.", "Screen close contacts."],
        "advice": common_advice,
    },
    "Common Cold": {
        "description": "Common cold is a viral upper respiratory infection causing runny nose, sneezing, cough, sore throat, and mild fever.",
        "medicines": ["Paracetamol", "Saline nasal spray", "Warm fluids"],
        "dosage": {"Paracetamol": "Use within safe limits for fever.", "Saline nasal spray": "1-2 sprays as needed.", "Warm fluids": "Sip frequently."},
        "precautions": ["Rest.", "Hydrate.", "Wash hands.", "Use mask if coughing."],
        "advice": common_advice,
    },
    "Pneumonia": {
        "description": "Pneumonia is lung infection causing cough, fever, chest pain, fast breathing, and breathlessness.",
        "medicines": ["Doctor-prescribed antibiotics", "Paracetamol", "Oxygen/supportive care if severe"],
        "dosage": {"Doctor-prescribed antibiotics": "Use only as prescribed.", "Paracetamol": "For fever within safe limits.", "Oxygen/supportive care if severe": "Hospital-supervised."},
        "precautions": ["Seek medical evaluation.", "Monitor breathing.", "Hydrate.", "Urgent care for breathlessness or low oxygen."],
        "advice": common_advice,
    },
    "Dimorphic hemmorhoids(piles)": {
        "description": "Piles are swollen anal veins that can cause pain, itching, bleeding, and discomfort while passing stool.",
        "medicines": ["Stool softener", "Local anesthetic gel", "Fiber supplement"],
        "dosage": {"Stool softener": "As per label or prescription.", "Local anesthetic gel": "Apply locally as advised.", "Fiber supplement": "Daily with water as per label."},
        "precautions": ["Eat fiber-rich food.", "Drink water.", "Avoid straining.", "Seek care for heavy bleeding."],
        "advice": common_advice,
    },
    "Heart attack": {
        "description": "Heart attack is a medical emergency caused by blocked blood flow to the heart, often with chest pain, sweating, nausea, or breathlessness.",
        "medicines": ["Emergency medical care", "Aspirin if advised by emergency provider", "Cardiac treatment"],
        "dosage": {"Emergency medical care": "Call emergency services immediately.", "Aspirin if advised by emergency provider": "Only if not allergic and advised.", "Cardiac treatment": "Hospital-supervised."},
        "precautions": ["Do not drive yourself.", "Call emergency services.", "Rest while waiting.", "Note symptom start time."],
        "advice": "Emergency warning: seek immediate medical care.",
    },
    "Varicose veins": {
        "description": "Varicose veins are enlarged twisted veins, usually in legs, causing aching, swelling, heaviness, or visible veins.",
        "medicines": ["Compression stockings", "Pain reliever", "Vascular consultation"],
        "dosage": {"Compression stockings": "Wear during daytime if advised.", "Pain reliever": "Paracetamol within safe limits if needed.", "Vascular consultation": "For persistent or severe cases."},
        "precautions": ["Elevate legs.", "Avoid standing for long periods.", "Walk regularly.", "Seek care for ulcers or sudden swelling."],
        "advice": common_advice,
    },
    "Hypothyroidism": {
        "description": "Hypothyroidism is underactive thyroid hormone production, causing fatigue, weight gain, cold intolerance, constipation, or dry skin.",
        "medicines": ["Levothyroxine", "Thyroid testing", "Dietary support"],
        "dosage": {"Levothyroxine": "Dose must be prescribed based on TSH.", "Thyroid testing": "Repeat as advised.", "Dietary support": "Balanced diet with adequate iodine unless restricted."},
        "precautions": ["Do TSH testing.", "Take medicine on empty stomach if prescribed.", "Do not change dose without doctor.", "Follow up regularly."],
        "advice": common_advice,
    },
    "Hyperthyroidism": {
        "description": "Hyperthyroidism is excess thyroid hormone causing weight loss, fast heartbeat, sweating, anxiety, tremor, or heat intolerance.",
        "medicines": ["Anti-thyroid medicine", "Beta blocker", "Thyroid testing"],
        "dosage": {"Anti-thyroid medicine": "Specialist-prescribed only.", "Beta blocker": "Use only if prescribed.", "Thyroid testing": "As advised."},
        "precautions": ["Consult endocrinologist.", "Monitor pulse.", "Avoid excess caffeine.", "Seek urgent care for very fast heartbeat or fever."],
        "advice": common_advice,
    },
    "Hypoglycemia": {
        "description": "Hypoglycemia is low blood sugar causing sweating, tremors, hunger, confusion, weakness, or fainting.",
        "medicines": ["Fast sugar source", "Glucose tablets", "Medical evaluation"],
        "dosage": {"Fast sugar source": "Take 15 g fast carbohydrate if conscious, then recheck.", "Glucose tablets": "Use as per label.", "Medical evaluation": "Needed for repeated episodes."},
        "precautions": ["Do not skip meals.", "Carry sugar if diabetic.", "Check glucose.", "Seek emergency help if unconscious."],
        "advice": common_advice,
    },
    "Osteoarthristis": {
        "description": "Osteoarthritis is joint wear-and-tear causing pain, stiffness, swelling, and reduced movement.",
        "medicines": ["Paracetamol", "Topical NSAID gel", "Physiotherapy"],
        "dosage": {"Paracetamol": "Use within safe daily limit.", "Topical NSAID gel": "Apply locally 2-3 times daily.", "Physiotherapy": "Regular exercises as advised."},
        "precautions": ["Maintain healthy weight.", "Do low-impact exercise.", "Avoid overloading joints.", "Use support if needed."],
        "advice": common_advice,
    },
    "Arthritis": {
        "description": "Arthritis is joint inflammation causing pain, swelling, stiffness, and limited movement.",
        "medicines": ["Paracetamol", "Anti-inflammatory medicine", "Physiotherapy"],
        "dosage": {"Paracetamol": "Use within safe limits.", "Anti-inflammatory medicine": "Only if suitable and advised.", "Physiotherapy": "As advised."},
        "precautions": ["Rest during flares.", "Do gentle movement.", "Seek evaluation for persistent swelling.", "Avoid self-medicating long term."],
        "advice": common_advice,
    },
    "(vertigo) Paroymsal  Positional Vertigo": {
        "description": "Benign positional vertigo causes brief spinning sensations triggered by head position changes.",
        "medicines": ["Vestibular exercises", "Meclizine", "Hydration"],
        "dosage": {"Vestibular exercises": "Do only as instructed.", "Meclizine": "Use only if prescribed.", "Hydration": "Drink fluids regularly."},
        "precautions": ["Avoid sudden head movements.", "Sit or lie down during dizziness.", "Do not drive while dizzy.", "Seek care for weakness or speech trouble."],
        "advice": common_advice,
    },
    "Acne": {
        "description": "Acne is blockage and inflammation of skin oil glands causing pimples, blackheads, or cysts.",
        "medicines": ["Benzoyl peroxide gel", "Salicylic acid wash", "Dermatology medicine"],
        "dosage": {"Benzoyl peroxide gel": "Apply thinly once daily initially.", "Salicylic acid wash": "Use once daily if tolerated.", "Dermatology medicine": "As prescribed."},
        "precautions": ["Do not squeeze pimples.", "Use non-comedogenic products.", "Wash face gently.", "Use sunscreen."],
        "advice": common_advice,
    },
    "Urinary tract infection": {
        "description": "UTI is infection in the urinary system causing burning urination, frequent urination, lower abdominal pain, or fever.",
        "medicines": ["Doctor-prescribed antibiotics", "ORS/water", "Urine alkalizer if advised"],
        "dosage": {"Doctor-prescribed antibiotics": "Take only after prescription and complete course.", "ORS/water": "Hydrate regularly.", "Urine alkalizer if advised": "Use as directed."},
        "precautions": ["Drink water.", "Do urine test.", "Do not delay care if fever/back pain.", "Maintain hygiene."],
        "advice": common_advice,
    },
    "Psoriasis": {
        "description": "Psoriasis is a chronic inflammatory skin condition causing scaly, itchy, red plaques.",
        "medicines": ["Moisturizer", "Topical steroid", "Dermatology therapy"],
        "dosage": {"Moisturizer": "Apply multiple times daily.", "Topical steroid": "Use only as prescribed.", "Dermatology therapy": "As advised."},
        "precautions": ["Avoid scratching.", "Moisturize skin.", "Avoid triggers like stress or harsh soaps.", "Follow dermatologist care."],
        "advice": common_advice,
    },
    "Impetigo": {
        "description": "Impetigo is a contagious bacterial skin infection causing red sores and honey-colored crusts, often around nose or mouth.",
        "medicines": ["Topical antibiotic", "Oral antibiotic", "Antiseptic cleansing"],
        "dosage": {"Topical antibiotic": "Apply as prescribed.", "Oral antibiotic": "Complete full course if prescribed.", "Antiseptic cleansing": "Clean gently once or twice daily."},
        "precautions": ["Avoid touching sores.", "Do not share towels.", "Keep nails short.", "Cover lesions if possible."],
        "advice": common_advice,
    },
}

data.update(diseases)
path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"Updated {path} with {len(diseases)} disease entries. Total entries: {len(data)}")
